# -*- coding: utf-8 -*-
"""model_teacher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnaR2MIaI3KRPsA0tzedfKEdugrZNXzu
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile model_teacher.py
# from transformers import AutoModelForSequenceClassification
# 
# def get_teacher(config):
#     model = AutoModelForSequenceClassification.from_pretrained(
#         config.model_teacher,
#         num_labels=config.num_labels,
#         output_hidden_states=True
#     )
#     for param in model.parameters():
#         param.requires_grad = False
#     return model