# -*- coding: utf-8 -*-
"""model_student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tl8Pj36BqpVc559xES7cGQ11l661Ig0a
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile model_student.py
# from transformers import BertConfig, BertForSequenceClassification
# 
# def get_student(config):
#     student_config = BertConfig.from_pretrained(
#         config.model_teacher,
#         num_hidden_layers=config.student_num_layers,
#         num_labels=config.num_labels,
#         output_hidden_states=True
#     )
#     model = BertForSequenceClassification(student_config)
#     return model