# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDYqL0H62nSl4ttYZlfViHhx8buqwhf6
"""

!python train_distill.py